# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/niko/workspace/easyP2P/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 391)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 10, 471, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 361, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_bondora = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_bondora.setObjectName("checkBox_bondora")
        self.gridLayout.addWidget(self.checkBox_bondora, 0, 0, 1, 1)
        self.checkBox_grupeer = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_grupeer.setObjectName("checkBox_grupeer")
        self.gridLayout.addWidget(self.checkBox_grupeer, 2, 0, 1, 1)
        self.checkBox_dofinance = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_dofinance.setObjectName("checkBox_dofinance")
        self.gridLayout.addWidget(self.checkBox_dofinance, 1, 0, 1, 1)
        self.checkBox_iuvo = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_iuvo.setObjectName("checkBox_iuvo")
        self.gridLayout.addWidget(self.checkBox_iuvo, 4, 0, 1, 1)
        self.checkBox_peerberry = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_peerberry.setObjectName("checkBox_peerberry")
        self.gridLayout.addWidget(self.checkBox_peerberry, 1, 1, 1, 1)
        self.checkBox_mintos = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_mintos.setObjectName("checkBox_mintos")
        self.gridLayout.addWidget(self.checkBox_mintos, 0, 1, 1, 1)
        self.checkBox_robocash = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_robocash.setObjectName("checkBox_robocash")
        self.gridLayout.addWidget(self.checkBox_robocash, 2, 1, 1, 1)
        self.checkBox_estateguru = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_estateguru.setObjectName("checkBox_estateguru")
        self.gridLayout.addWidget(self.checkBox_estateguru, 3, 0, 1, 1)
        self.checkBox_swaper = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_swaper.setObjectName("checkBox_swaper")
        self.gridLayout.addWidget(self.checkBox_swaper, 3, 1, 1, 1)
        self.checkBox_twino = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_twino.setObjectName("checkBox_twino")
        self.gridLayout.addWidget(self.checkBox_twino, 4, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 210, 451, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_start_month = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_start_month.setGeometry(QtCore.QRect(20, 30, 83, 32))
        self.comboBox_start_month.setObjectName("comboBox_start_month")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_month.addItem("")
        self.comboBox_start_year = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_start_year.setGeometry(QtCore.QRect(120, 30, 83, 32))
        self.comboBox_start_year.setObjectName("comboBox_start_year")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.comboBox_start_year.addItem("")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.comboBox_end_month = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_end_month.setGeometry(QtCore.QRect(20, 30, 83, 32))
        self.comboBox_end_month.setObjectName("comboBox_end_month")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_month.addItem("")
        self.comboBox_end_year = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_end_year.setGeometry(QtCore.QRect(120, 30, 83, 32))
        self.comboBox_end_year.setObjectName("comboBox_end_year")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.comboBox_end_year.addItem("")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_start.setGeometry(QtCore.QRect(170, 310, 141, 34))
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.groupBox)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Für welche P2P-Plattformen sollen Ergebnisse geladen werden?"))
        self.checkBox_bondora.setText(_translate("MainWindow", "Bondora"))
        self.checkBox_grupeer.setText(_translate("MainWindow", "Grupeer"))
        self.checkBox_dofinance.setText(_translate("MainWindow", "DoFinance"))
        self.checkBox_iuvo.setText(_translate("MainWindow", "Iuvo"))
        self.checkBox_peerberry.setText(_translate("MainWindow", "PeerBerry"))
        self.checkBox_mintos.setText(_translate("MainWindow", "Mintos"))
        self.checkBox_robocash.setText(_translate("MainWindow", "Robocash"))
        self.checkBox_estateguru.setText(_translate("MainWindow", "Estateguru"))
        self.checkBox_swaper.setText(_translate("MainWindow", "Swaper"))
        self.checkBox_twino.setText(_translate("MainWindow", "Twino"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Startdatum"))
        self.comboBox_start_month.setItemText(0, _translate("MainWindow", "Jan"))
        self.comboBox_start_month.setItemText(1, _translate("MainWindow", "Feb"))
        self.comboBox_start_month.setItemText(2, _translate("MainWindow", "Mrz"))
        self.comboBox_start_month.setItemText(3, _translate("MainWindow", "Apr"))
        self.comboBox_start_month.setItemText(4, _translate("MainWindow", "Mai"))
        self.comboBox_start_month.setItemText(5, _translate("MainWindow", "Jun"))
        self.comboBox_start_month.setItemText(6, _translate("MainWindow", "Jul"))
        self.comboBox_start_month.setItemText(7, _translate("MainWindow", "Aug"))
        self.comboBox_start_month.setItemText(8, _translate("MainWindow", "Sep"))
        self.comboBox_start_month.setItemText(9, _translate("MainWindow", "Okt"))
        self.comboBox_start_month.setItemText(10, _translate("MainWindow", "Nov"))
        self.comboBox_start_month.setItemText(11, _translate("MainWindow", "Dez"))
        self.comboBox_start_year.setItemText(0, _translate("MainWindow", "2010"))
        self.comboBox_start_year.setItemText(1, _translate("MainWindow", "2011"))
        self.comboBox_start_year.setItemText(2, _translate("MainWindow", "2012"))
        self.comboBox_start_year.setItemText(3, _translate("MainWindow", "2013"))
        self.comboBox_start_year.setItemText(4, _translate("MainWindow", "2014"))
        self.comboBox_start_year.setItemText(5, _translate("MainWindow", "2015"))
        self.comboBox_start_year.setItemText(6, _translate("MainWindow", "2016"))
        self.comboBox_start_year.setItemText(7, _translate("MainWindow", "2017"))
        self.comboBox_start_year.setItemText(8, _translate("MainWindow", "2018"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Enddatum"))
        self.comboBox_end_month.setItemText(0, _translate("MainWindow", "Jan"))
        self.comboBox_end_month.setItemText(1, _translate("MainWindow", "Feb"))
        self.comboBox_end_month.setItemText(2, _translate("MainWindow", "Mrz"))
        self.comboBox_end_month.setItemText(3, _translate("MainWindow", "Apr"))
        self.comboBox_end_month.setItemText(4, _translate("MainWindow", "Mai"))
        self.comboBox_end_month.setItemText(5, _translate("MainWindow", "Jun"))
        self.comboBox_end_month.setItemText(6, _translate("MainWindow", "Jul"))
        self.comboBox_end_month.setItemText(7, _translate("MainWindow", "Aug"))
        self.comboBox_end_month.setItemText(8, _translate("MainWindow", "Sep"))
        self.comboBox_end_month.setItemText(9, _translate("MainWindow", "Okt"))
        self.comboBox_end_month.setItemText(10, _translate("MainWindow", "Nov"))
        self.comboBox_end_month.setItemText(11, _translate("MainWindow", "Dez"))
        self.comboBox_end_year.setItemText(0, _translate("MainWindow", "2010"))
        self.comboBox_end_year.setItemText(1, _translate("MainWindow", "2011"))
        self.comboBox_end_year.setItemText(2, _translate("MainWindow", "2012"))
        self.comboBox_end_year.setItemText(3, _translate("MainWindow", "2013"))
        self.comboBox_end_year.setItemText(4, _translate("MainWindow", "2014"))
        self.comboBox_end_year.setItemText(5, _translate("MainWindow", "2015"))
        self.comboBox_end_year.setItemText(6, _translate("MainWindow", "2016"))
        self.comboBox_end_year.setItemText(7, _translate("MainWindow", "2017"))
        self.comboBox_end_year.setItemText(8, _translate("MainWindow", "2018"))
        self.pushButton_start.setText(_translate("MainWindow", "Starte Auswertung"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

